version: '3.8'

services:
  postgresql:
    container_name: lish-postgresql
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    image: lish/db
    env_file:
      - docker/postgresql/.env
    ports:
      - "5432:5432"
    networks:
      - container-link
    volumes:
      - lish-postgresql-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
    logging:
      driver: json-file
      options:
        max-size: '5m'
        max-file: '1'

  pgadmin4:
    container_name: lish-pgadmin4
    image: dpage/pgadmin4:6.4
    env_file:
      - docker/pgadmin4/.env
    depends_on:
      - postgresql
    ports:
      - "5433:80"
    networks:
      - container-link
    volumes:
      - lish-pgadmin4-data:/var/lib/pgadmin:rw
    logging:
      driver: json-file
      options:
        max-size: '5m'
        max-file: '1'

  app:
    container_name: lish-backend-app
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    image: lish/backend-app
    depends_on:
      - postgresql
    ports:
      - "5434:8080"
    networks:
      - container-link
    volumes:
      - ./:/go/src/app:rw
    tty: true
    logging:
      driver: json-file
      options:
        max-size: '5m'
        max-file: '1'

networks:
  default:
    external:
      name: bridge
  container-link:
    name: lish.docker.internal

volumes:
  lish-postgresql-data:
    driver: local
  lish-pgadmin4-data:
    driver: local
